### ISSUE TITLE
Linux developer issues.

### ISSUE THREAD

**Issue by nihirash** [Fabrizio-Caruso/CROSS-CHASE#80]
There no tools for linux development(maybe sources of tools helps us). If there are sources - I think better will be add links to it in readme. 

```
make ncurses
```

Fails with `a.exe` not found - there better add output file name option. Or poor-mans variang - just run `a.out` on unixes(may be i'll try to fix makefiles to build ncurses target on *nixes). 

May be its time to sepparate library and game code bases? :smiley: 

Thank you for great library! :+1:

**Comment by Fabrizio-Caruso** [comment]
Yes, there must be a way to build most targets under Unix.
Most of my Makefile is Unix-friendly and many targets should work.
If you come up with something that fixes Unix compilation without breaking anything on Cygwin, please let me know!

The library and game code are separate!
src/chase <- game code
src/cross_lib <- library code

you could put a completly different game inside src/chase.

**Comment by nihirash** [comment]
I'll try to fix it and make PR

**Comment by Fabrizio-Caruso** [comment]
@nihirash thanks!
One thing to do would be to use Linux versions of some of the tools required for some targets or even better, use the source code of the tools and recompile them for Windows/Linux.

**Comment by Fabrizio-Caruso** [comment]
@nihirash I have recently added some targets that I can only compile under Linux due to the limitations of the ACK compiler.
I can now compile my game for the PC 8086, CP/M 8080, Linux PPC/386/68020 and even the PDP 11!

**Comment by Fabrizio-Caruso** [comment]
@nihirash I have just made a little improvement in the Makefile that allows the build of the ncurses version in both Cygwin and Unix.

**Comment by Fabrizio-Caruso** [comment]
@nihirash the ncurses problem has been solved. I am going to close this issue but I know that the Makefile is not perfect with a few Windows-only (e.g., cpc)  and Unix-only (all ACK targets) cases.
Please let me know if you are working on fixing the remainig cases.
